from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestManyAnswers(object):
    def setupUi(self, QuestManyAnswers):
        QuestManyAnswers.setObjectName("QuestManyAnswers")
        QuestManyAnswers.resize(900, 500)
        QuestManyAnswers.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(QuestManyAnswers)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clue_quest_2 = QtWidgets.QLabel(QuestManyAnswers)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clue_quest_2.setFont(font)
        self.clue_quest_2.setObjectName("clue_quest_2")
        self.horizontalLayout_2.addWidget(self.clue_quest_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.question_text_browser = QtWidgets.QTextBrowser(QuestManyAnswers)
        self.question_text_browser.setMinimumSize(QtCore.QSize(500, 50))
        self.question_text_browser.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.question_text_browser.setFont(font)
        self.question_text_browser.setObjectName("question_text_browser")
        self.horizontalLayout_3.addWidget(self.question_text_browser)
        self.picture_label = QtWidgets.QLabel(QuestManyAnswers)
        self.picture_label.setText("")
        self.picture_label.setObjectName("picture_label")
        self.horizontalLayout_3.addWidget(self.picture_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clue_answers_2 = QtWidgets.QLabel(QuestManyAnswers)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clue_answers_2.setFont(font)
        self.clue_answers_2.setObjectName("clue_answers_2")
        self.horizontalLayout.addWidget(self.clue_answers_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.answer1_check_box = QtWidgets.QCheckBox(QuestManyAnswers)
        self.answer1_check_box.setText("")
        self.answer1_check_box.setObjectName("answer1_check_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.answer1_check_box)
        self.answer1_text_browser_2 = QtWidgets.QTextBrowser(QuestManyAnswers)
        self.answer1_text_browser_2.setMinimumSize(QtCore.QSize(10, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.answer1_text_browser_2.setFont(font)
        self.answer1_text_browser_2.setObjectName("answer1_text_browser_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.answer1_text_browser_2)
        self.answer2_check_box = QtWidgets.QCheckBox(QuestManyAnswers)
        self.answer2_check_box.setText("")
        self.answer2_check_box.setObjectName("answer2_check_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.answer2_check_box)
        self.answer2_text_browser_2 = QtWidgets.QTextBrowser(QuestManyAnswers)
        self.answer2_text_browser_2.setMinimumSize(QtCore.QSize(10, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.answer2_text_browser_2.setFont(font)
        self.answer2_text_browser_2.setObjectName("answer2_text_browser_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.answer2_text_browser_2)
        self.answer3_check_box = QtWidgets.QCheckBox(QuestManyAnswers)
        self.answer3_check_box.setText("")
        self.answer3_check_box.setObjectName("answer3_check_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.answer3_check_box)
        self.answer3_text_browser_2 = QtWidgets.QTextBrowser(QuestManyAnswers)
        self.answer3_text_browser_2.setMinimumSize(QtCore.QSize(10, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.answer3_text_browser_2.setFont(font)
        self.answer3_text_browser_2.setObjectName("answer3_text_browser_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.answer3_text_browser_2)
        self.answer4_check_box = QtWidgets.QCheckBox(QuestManyAnswers)
        self.answer4_check_box.setText("")
        self.answer4_check_box.setObjectName("answer4_check_box")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.answer4_check_box)
        self.answer4_text_browser_2 = QtWidgets.QTextBrowser(QuestManyAnswers)
        self.answer4_text_browser_2.setMinimumSize(QtCore.QSize(10, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.answer4_text_browser_2.setFont(font)
        self.answer4_text_browser_2.setObjectName("answer4_text_browser_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.answer4_text_browser_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.confirm_push_button = QtWidgets.QPushButton(QuestManyAnswers)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.confirm_push_button.setFont(font)
        self.confirm_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.confirm_push_button.setObjectName("confirm_push_button")
        self.verticalLayout.addWidget(self.confirm_push_button)

        self.retranslateUi(QuestManyAnswers)
        QtCore.QMetaObject.connectSlotsByName(QuestManyAnswers)

    def retranslateUi(self, QuestManyAnswers):
        _translate = QtCore.QCoreApplication.translate
        QuestManyAnswers.setWindowTitle(_translate("QuestManyAnswers", "Form"))
        self.clue_quest_2.setText(_translate("QuestManyAnswers", "Вопрос:"))
        self.clue_answers_2.setText(_translate("QuestManyAnswers", "Выберите ответ:"))
        self.answer1_text_browser_2.setHtml(_translate("QuestManyAnswers",
                                                       "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                       "p, li { white-space: pre-wrap; }\n"
                                                       "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                                       "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.confirm_push_button.setText(_translate("QuestManyAnswers", "Подтвердить"))
