# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CreateTestingFinish.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateTestingFinish(object):
    def setupUi(self, Ui_CreateTestingFinish):
        Ui_CreateTestingFinish.setObjectName("CreateTestingChoiceTagAndName")
        Ui_CreateTestingFinish.resize(400, 104)
        Ui_CreateTestingFinish.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_CreateTestingFinish)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hint_tags_label = QtWidgets.QLabel(Ui_CreateTestingFinish)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_tags_label.setFont(font)
        self.hint_tags_label.setObjectName("hint_tags_label")
        self.horizontalLayout_3.addWidget(self.hint_tags_label)
        self.all_tags_combo_box = QtWidgets.QComboBox(Ui_CreateTestingFinish)
        self.all_tags_combo_box.setObjectName("all_tags_combo_box")
        self.horizontalLayout_3.addWidget(self.all_tags_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hint_name_label = QtWidgets.QLabel(Ui_CreateTestingFinish)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_name_label.setFont(font)
        self.hint_name_label.setObjectName("hint_name_label")
        self.horizontalLayout_2.addWidget(self.hint_name_label)
        self.name_line_edit = QtWidgets.QLineEdit(Ui_CreateTestingFinish)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.name_line_edit.setFont(font)
        self.name_line_edit.setMaxLength(200)
        self.name_line_edit.setObjectName("name_line_edit")
        self.horizontalLayout_2.addWidget(self.name_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.create_push_button = QtWidgets.QPushButton(Ui_CreateTestingFinish)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_push_button.setFont(font)
        self.create_push_button.setStyleSheet("QPushButton { background-color: rgb(213, 122, 9);}\n"
                                              "QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                              "QPushButton:disabled{ background:#a2979c; }")
        self.create_push_button.setObjectName("create_push_button")
        self.horizontalLayout.addWidget(self.create_push_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Ui_CreateTestingFinish)
        QtCore.QMetaObject.connectSlotsByName(Ui_CreateTestingFinish)

    def retranslateUi(self, CreateTestingChoiceTagAndName):
        _translate = QtCore.QCoreApplication.translate
        CreateTestingChoiceTagAndName.setWindowTitle(_translate("CreateTestingChoiceTagAndName", "Form"))
        self.hint_tags_label.setText(_translate("CreateTestingChoiceTagAndName", "Тег"))
        self.hint_name_label.setText(_translate("CreateTestingChoiceTagAndName", "Название"))
        self.create_push_button.setText(_translate("CreateTestingChoiceTagAndName", "Создать"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    CreateTestingChoiceTagAndName = QtWidgets.QWidget()
    ui = Ui_CreateTestingFinish()
    ui.setupUi(CreateTestingChoiceTagAndName)
    CreateTestingChoiceTagAndName.show()
    sys.exit(app.exec_())
