# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CreateTagDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_CreateTagDialog(object):
    def setupUi(self, Ui_CreateTagDialog):
        Ui_CreateTagDialog.setObjectName("Ui_CreateTagDialog")
        Ui_CreateTagDialog.setWindowModality(QtCore.Qt.NonModal)
        Ui_CreateTagDialog.resize(345, 113)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_CreateTagDialog.sizePolicy().hasHeightForWidth())
        Ui_CreateTagDialog.setSizePolicy(sizePolicy)
        Ui_CreateTagDialog.setMinimumSize(QtCore.QSize(345, 113))
        Ui_CreateTagDialog.setMaximumSize(QtCore.QSize(345, 113))
        Ui_CreateTagDialog.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_CreateTagDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hint_name_label = QtWidgets.QLabel(Ui_CreateTagDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_name_label.setFont(font)
        self.hint_name_label.setObjectName("hint_name_label")
        self.horizontalLayout.addWidget(self.hint_name_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.name_line_edit = QtWidgets.QLineEdit(Ui_CreateTagDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_line_edit.setFont(font)
        self.name_line_edit.setObjectName("name_line_edit")
        self.verticalLayout.addWidget(self.name_line_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.create_tag_push_button = QtWidgets.QPushButton(Ui_CreateTagDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.create_tag_push_button.setFont(font)
        self.create_tag_push_button.setStyleSheet("QPushButton { background-color: rgb(213, 122, 9);}\n"
"QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
"QPushButton:disabled{ background:#a2979c; }")
        self.create_tag_push_button.setObjectName("create_tag_push_button")
        self.horizontalLayout_2.addWidget(self.create_tag_push_button)
        self.cancel_push_button = QtWidgets.QPushButton(Ui_CreateTagDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_push_button.setFont(font)
        self.cancel_push_button.setStyleSheet("QPushButton { background-color: rgb(213, 122, 9);}\n"
"QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
"QPushButton:disabled{ background:#a2979c; }")
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.horizontalLayout_2.addWidget(self.cancel_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Ui_CreateTagDialog)
        QtCore.QMetaObject.connectSlotsByName(Ui_CreateTagDialog)

    def retranslateUi(self, Ui_CreateTagDialog):
        _translate = QtCore.QCoreApplication.translate
        Ui_CreateTagDialog.setWindowTitle(_translate("Ui_CreateTagDialog", "Form"))
        self.hint_name_label.setText(_translate("Ui_CreateTagDialog", "Название тега"))
        self.create_tag_push_button.setText(_translate("Ui_CreateTagDialog", "Создать"))
        self.cancel_push_button.setText(_translate("Ui_CreateTagDialog", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_CreateTagDialog = QtWidgets.QWidget()
    ui = Ui_Ui_CreateTagDialog()
    ui.setupUi(Ui_CreateTagDialog)
    Ui_CreateTagDialog.show()
    sys.exit(app.exec_())
