# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ChangeUserGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_ChangeUserGroup(object):
    def setupUi(self, Ui_ChangeUserGroup):
        Ui_ChangeUserGroup.setObjectName("Ui_ChangeUserGroup")
        Ui_ChangeUserGroup.resize(270, 90)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_ChangeUserGroup.sizePolicy().hasHeightForWidth())
        Ui_ChangeUserGroup.setSizePolicy(sizePolicy)
        Ui_ChangeUserGroup.setMinimumSize(QtCore.QSize(270, 90))
        Ui_ChangeUserGroup.setMaximumSize(QtCore.QSize(300, 90))
        Ui_ChangeUserGroup.setStyleSheet("color: rgb(255, 255, 255); background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui_ChangeUserGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hint_name_label = QtWidgets.QLabel(Ui_ChangeUserGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_name_label.setFont(font)
        self.hint_name_label.setObjectName("hint_name_label")
        self.horizontalLayout.addWidget(self.hint_name_label)
        self.groups_combo_box = QtWidgets.QComboBox(Ui_ChangeUserGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groups_combo_box.setFont(font)
        self.groups_combo_box.setObjectName("groups_combo_box")
        self.horizontalLayout.addWidget(self.groups_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.change_push_button = QtWidgets.QPushButton(Ui_ChangeUserGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.change_push_button.setFont(font)
        self.change_push_button.setStyleSheet("QPushButton { background-color: rgb(213, 122, 9);}\n"
"QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
"QPushButton:disabled{ background:#a2979c; }")
        self.change_push_button.setObjectName("change_push_button")
        self.horizontalLayout_2.addWidget(self.change_push_button)
        self.cancel_push_button = QtWidgets.QPushButton(Ui_ChangeUserGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_push_button.setFont(font)
        self.cancel_push_button.setStyleSheet("QPushButton { background-color: rgb(213, 122, 9);}\n"
"QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
"QPushButton:disabled{ background:#a2979c; }")
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.horizontalLayout_2.addWidget(self.cancel_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Ui_ChangeUserGroup)
        QtCore.QMetaObject.connectSlotsByName(Ui_ChangeUserGroup)

    def retranslateUi(self, Ui_ChangeUserGroup):
        _translate = QtCore.QCoreApplication.translate
        Ui_ChangeUserGroup.setWindowTitle(_translate("Ui_ChangeUserGroup", "Form"))
        self.hint_name_label.setText(_translate("Ui_ChangeUserGroup", "Установить группу"))
        self.change_push_button.setText(_translate("Ui_ChangeUserGroup", "Изменить"))
        self.cancel_push_button.setText(_translate("Ui_ChangeUserGroup", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_ChangeUserGroup = QtWidgets.QWidget()
    ui = Ui_Ui_ChangeUserGroup()
    ui.setupUi(Ui_ChangeUserGroup)
    Ui_ChangeUserGroup.show()
    sys.exit(app.exec_())
