from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authentication(object):
    def setupUi(self, Authentication):
        Authentication.setObjectName("Authentication")
        Authentication.resize(969, 692)
        Authentication.setStyleSheet("QLabel\n"
                                     "{\n"
                                     "    color: white;\n"
                                     "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Authentication)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_widget = QtWidgets.QWidget(Authentication)
        self.left_widget.setStyleSheet("background-color: rgb(13, 130, 149);")
        self.left_widget.setObjectName("left_widget")
        self.horizontalLayout.addWidget(self.left_widget)
        self.center_widget = QtWidgets.QWidget(Authentication)
        self.center_widget.setMinimumSize(QtCore.QSize(350, 0))
        self.center_widget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.center_widget.setStyleSheet("background-color: rgb(203, 122, 9);")
        self.center_widget.setObjectName("center_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.center_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setSpacing(0)
        self.vertical_layout.setObjectName("vertical_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem)
        self.tab_widget_authorization = QtWidgets.QTabWidget(self.center_widget)
        self.tab_widget_authorization.setMinimumSize(QtCore.QSize(350, 400))
        self.tab_widget_authorization.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_widget_authorization.setFont(font)
        self.tab_widget_authorization.setStyleSheet("QTabWidget::pane\n"
                                                    "{\n"
                                                    "    border:1px;\n"
                                                    "    background: rgb(203, 122, 9);\n"
                                                    "}\n"
                                                    "QTabBar::tab\n"
                                                    "{\n"
                                                    "    color: white;\n"
                                                    "    background: rgb(203, 122, 9);\n"
                                                    "    min-width: 25ex;\n"
                                                    "    min-height: 8ex;\n"
                                                    "}\n"
                                                    "QTabBar::tab::selected { background: rgb(13, 130, 149); }\n"
                                                    "QTabBar::tab::hover { background: rgb(203, 112, 9); }")
        self.tab_widget_authorization.setObjectName("tab_widget_authorization")
        self.authorization = QtWidgets.QWidget()
        self.authorization.setStyleSheet("")
        self.authorization.setObjectName("authorization")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.authorization)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.form_layout_radio_button = QtWidgets.QFormLayout()
        self.form_layout_radio_button.setObjectName("form_layout_radio_button")
        self.how_user_radio_button = QtWidgets.QRadioButton(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.how_user_radio_button.setFont(font)
        self.how_user_radio_button.setStyleSheet("    color: white;")
        self.how_user_radio_button.setChecked(True)
        self.how_user_radio_button.setObjectName("how_user_radio_button")
        self.form_layout_radio_button.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.how_user_radio_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.form_layout_radio_button.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.how_admin_radio_button = QtWidgets.QRadioButton(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.how_admin_radio_button.setFont(font)
        self.how_admin_radio_button.setStyleSheet("    color: white;")
        self.how_admin_radio_button.setObjectName("how_admin_radio_button")
        self.form_layout_radio_button.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.how_admin_radio_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.form_layout_radio_button.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout_3.addLayout(self.form_layout_radio_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.login_label = QtWidgets.QLabel(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_label.setFont(font)
        self.login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_label.setObjectName("login_label")
        self.verticalLayout_3.addWidget(self.login_label)
        self.login_line_edit = QtWidgets.QLineEdit(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_line_edit.setFont(font)
        self.login_line_edit.setMaxLength(64)
        self.login_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.login_line_edit.setObjectName("login_line_edit")
        self.verticalLayout_3.addWidget(self.login_line_edit)
        self.password_label = QtWidgets.QLabel(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_label.setFont(font)
        self.password_label.setTextFormat(QtCore.Qt.AutoText)
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.verticalLayout_3.addWidget(self.password_label)
        self.password_line_edit = QtWidgets.QLineEdit(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setInputMask("")
        self.password_line_edit.setText("")
        self.password_line_edit.setMaxLength(60)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line_edit.setObjectName("password_line_edit")
        self.verticalLayout_3.addWidget(self.password_line_edit)
        self.login_button = QtWidgets.QPushButton(self.authorization)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("color: white;\n"
                                        "background: rgb(13, 130, 149);")
        self.login_button.setObjectName("login_button")
        self.verticalLayout_3.addWidget(self.login_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.hint_authorization_text_browser = QtWidgets.QTextBrowser(self.authorization)
        self.hint_authorization_text_browser.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_authorization_text_browser.setFont(font)
        self.hint_authorization_text_browser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint_authorization_text_browser.setStyleSheet("border:  rgb(203, 122, 9);\n"
                                                           "color: rgb(255, 0, 0)")
        self.hint_authorization_text_browser.setObjectName("hint_authorization_text_browser")
        self.verticalLayout_3.addWidget(self.hint_authorization_text_browser)
        self.tab_widget_authorization.addTab(self.authorization, "")
        self.registration = QtWidgets.QWidget()
        self.registration.setStyleSheet("")
        self.registration.setObjectName("registration")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.registration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_layout_register = QtWidgets.QFormLayout()
        self.form_layout_register.setLabelAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.form_layout_register.setObjectName("form_layout_register")
        self.surname_label = QtWidgets.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.surname_label.setFont(font)
        self.surname_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.surname_label.setObjectName("surname_label")
        self.form_layout_register.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.surname_label)
        self.surname_line_edit = QtWidgets.QLineEdit(self.registration)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.surname_line_edit.setFont(font)
        self.surname_line_edit.setMaxLength(64)
        self.surname_line_edit.setObjectName("surname_line_edit")
        self.form_layout_register.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.surname_line_edit)
        self.name_label = QtWidgets.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.form_layout_register.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_line_edit = QtWidgets.QLineEdit(self.registration)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name_line_edit.setFont(font)
        self.name_line_edit.setMaxLength(64)
        self.name_line_edit.setObjectName("name_line_edit")
        self.form_layout_register.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_line_edit)
        self.patronymic_label = QtWidgets.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patronymic_label.setFont(font)
        self.patronymic_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.patronymic_label.setObjectName("patronymic_label")
        self.form_layout_register.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.patronymic_label)
        self.patronymic_line_edit = QtWidgets.QLineEdit(self.registration)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.patronymic_line_edit.setFont(font)
        self.patronymic_line_edit.setMaxLength(64)
        self.patronymic_line_edit.setObjectName("patronymic_line_edit")
        self.form_layout_register.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.patronymic_line_edit)
        self.login_label_2 = QtWidgets.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_label_2.setFont(font)
        self.login_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.login_label_2.setObjectName("login_label_2")
        self.form_layout_register.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.login_label_2)
        self.login_line_edit_register = QtWidgets.QLineEdit(self.registration)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_line_edit_register.setFont(font)
        self.login_line_edit_register.setMaxLength(64)
        self.login_line_edit_register.setObjectName("login_line_edit_register")
        self.form_layout_register.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.login_line_edit_register)
        self.password_label_2 = QtWidgets.QLabel(self.registration)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label_2.setFont(font)
        self.password_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.password_label_2.setObjectName("password_label_2")
        self.form_layout_register.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.password_label_2)
        self.password_line_edit_register = QtWidgets.QLineEdit(self.registration)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_line_edit_register.setFont(font)
        self.password_line_edit_register.setMaxLength(60)
        self.password_line_edit_register.setObjectName("password_line_edit_register")
        self.form_layout_register.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password_line_edit_register)
        self.verticalLayout.addLayout(self.form_layout_register)
        self.register_button = QtWidgets.QPushButton(self.registration)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background: rgb(13, 130, 149);")
        self.register_button.setObjectName("register_button")
        self.verticalLayout.addWidget(self.register_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 109, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.hint_registration_text_browser = QtWidgets.QTextBrowser(self.registration)
        self.hint_registration_text_browser.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_registration_text_browser.setFont(font)
        self.hint_registration_text_browser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hint_registration_text_browser.setStyleSheet("border:  rgb(203, 122, 9);\n"
                                                          "color: rgb(255, 0, 0)")
        self.hint_registration_text_browser.setObjectName("hint_registration_text_browser")
        self.verticalLayout.addWidget(self.hint_registration_text_browser)
        self.tab_widget_authorization.addTab(self.registration, "")
        self.vertical_layout.addWidget(self.tab_widget_authorization)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.vertical_layout)
        self.horizontalLayout.addWidget(self.center_widget)
        self.right_widget = QtWidgets.QWidget(Authentication)
        self.right_widget.setStyleSheet("background-color: rgb(13, 130, 149);")
        self.right_widget.setObjectName("right_widget")
        self.horizontalLayout.addWidget(self.right_widget)

        self.retranslateUi(Authentication)
        self.tab_widget_authorization.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Authentication)

    def retranslateUi(self, Authentication):
        _translate = QtCore.QCoreApplication.translate
        Authentication.setWindowTitle(_translate("Authentication", "Form"))
        self.how_user_radio_button.setText(_translate("Authentication", "Войти как пользователь"))
        self.how_admin_radio_button.setText(_translate("Authentication", "Войти как администратор"))
        self.login_label.setText(_translate("Authentication", "Ваш логин"))
        self.login_line_edit.setPlaceholderText(_translate("Authentication", "Логин..."))
        self.password_label.setText(_translate("Authentication", "Введите пароль"))
        self.password_line_edit.setPlaceholderText(_translate("Authentication", "Пароль..."))
        self.login_button.setText(_translate("Authentication", "Войти"))
        self.hint_authorization_text_browser.setHtml(_translate("Authentication",
                                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                "p, li { white-space: pre-wrap; }\n"
                                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tab_widget_authorization.setTabText(self.tab_widget_authorization.indexOf(self.authorization),
                                                 _translate("Authentication", "Авторизация"))
        self.surname_label.setText(_translate("Authentication", "Фамилия"))
        self.surname_line_edit.setPlaceholderText(_translate("Authentication", "Ваше фамилия..."))
        self.name_label.setText(_translate("Authentication", "Имя"))
        self.name_line_edit.setPlaceholderText(_translate("Authentication", "Ваше имя..."))
        self.patronymic_label.setText(_translate("Authentication", "Отчество"))
        self.patronymic_line_edit.setPlaceholderText(_translate("Authentication", "Ваше отчество..."))
        self.login_label_2.setText(_translate("Authentication", "Логин"))
        self.login_line_edit_register.setPlaceholderText(_translate("Authentication", "Придумайте логин..."))
        self.password_label_2.setText(_translate("Authentication", "Пароль"))
        self.password_line_edit_register.setPlaceholderText(_translate("Authentication", "Придумайте пароль..."))
        self.register_button.setText(_translate("Authentication", "Зарегистрироваться"))
        self.hint_registration_text_browser.setHtml(_translate("Authentication",
                                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                               "p, li { white-space: pre-wrap; }\n"
                                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tab_widget_authorization.setTabText(self.tab_widget_authorization.indexOf(self.registration),
                                                 _translate("Authentication", "Регистрация"))
