from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListSearch(object):
    def setupUi(self, ListSearch):
        ListSearch.setObjectName("ListSearch")
        ListSearch.resize(864, 506)
        ListSearch.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(ListSearch)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab_widget = QtWidgets.QTabWidget(ListSearch)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.main_tab_widget.setFont(font)
        self.main_tab_widget.setStyleSheet("QTabWidget::pane\n"
                                           "{\n"
                                           "    border:1px;\n"
                                           "    background: rgb(203, 122, 9);\n"
                                           "}\n"
                                           "\n"
                                           "QTabBar::tab\n"
                                           "{\n"
                                           "    color: white;\n"
                                           "    background: rgb(13, 120, 149);\n"
                                           "    min-width: 25ex;\n"
                                           "    min-height: 8ex;\n"
                                           "}\n"
                                           "\n"
                                           "QTabBar::tab::selected\n"
                                           "{\n"
                                           "    background: rgb(213, 122, 9);\n"
                                           "}\n"
                                           "\n"
                                           "QTabBar::tab::hover\n"
                                           "{\n"
                                           "    background: rgb(203, 112, 9);\n"
                                           "}\n"
                                           "")
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_search)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_search1 = QtWidgets.QTabWidget(self.tab_search)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_search1.setFont(font)
        self.tab_search1.setObjectName("tab_search1")
        self.tab_tests = QtWidgets.QWidget()
        self.tab_tests.setObjectName("tab_tests")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_tests)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontal_layout_chenge_search_test = QtWidgets.QHBoxLayout()
        self.horizontal_layout_chenge_search_test.setObjectName("horizontal_layout_chenge_search_test")
        self.clue_test1 = QtWidgets.QLabel(self.tab_tests)
        self.clue_test1.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clue_test1.setFont(font)
        self.clue_test1.setObjectName("clue_test1")
        self.horizontal_layout_chenge_search_test.addWidget(self.clue_test1)
        self.change_search_on_test_combo_box = QtWidgets.QComboBox(self.tab_tests)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_search_on_test_combo_box.sizePolicy().hasHeightForWidth())
        self.change_search_on_test_combo_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.change_search_on_test_combo_box.setFont(font)
        self.change_search_on_test_combo_box.setObjectName("change_search_on_test_combo_box")
        self.change_search_on_test_combo_box.addItem("")
        self.change_search_on_test_combo_box.addItem("")
        self.horizontal_layout_chenge_search_test.addWidget(self.change_search_on_test_combo_box)
        spacerItem = QtWidgets.QSpacerItem(669, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_chenge_search_test.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontal_layout_chenge_search_test)
        self.horizontal_layout_edit_search_test = QtWidgets.QHBoxLayout()
        self.horizontal_layout_edit_search_test.setObjectName("horizontal_layout_edit_search_test")
        self.search_on_tests_line_edit = QtWidgets.QLineEdit(self.tab_tests)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_on_tests_line_edit.sizePolicy().hasHeightForWidth())
        self.search_on_tests_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_on_tests_line_edit.setFont(font)
        self.search_on_tests_line_edit.setObjectName("search_on_tests_line_edit")
        self.horizontal_layout_edit_search_test.addWidget(self.search_on_tests_line_edit)
        self.find_test_button = QtWidgets.QPushButton(self.tab_tests)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_test_button.sizePolicy().hasHeightForWidth())
        self.find_test_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_test_button.setFont(font)
        self.find_test_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.find_test_button.setObjectName("find_test_button")
        self.horizontal_layout_edit_search_test.addWidget(self.find_test_button)
        self.refresh_test_button = QtWidgets.QPushButton(self.tab_tests)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refresh_test_button.setFont(font)
        self.refresh_test_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.refresh_test_button.setObjectName("refresh_test_button")
        self.horizontal_layout_edit_search_test.addWidget(self.refresh_test_button)
        self.verticalLayout_2.addLayout(self.horizontal_layout_edit_search_test)
        self.clue_test2 = QtWidgets.QLabel(self.tab_tests)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clue_test2.setFont(font)
        self.clue_test2.setObjectName("clue_test2")
        self.verticalLayout_2.addWidget(self.clue_test2)
        self.test_table_widget = QtWidgets.QTableWidget(self.tab_tests)
        self.test_table_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
                                             "background-color: rgb(255, 255, 255);")
        self.test_table_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.test_table_widget.setObjectName("test_table_widget")
        self.test_table_widget.setColumnCount(4)
        self.test_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.test_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_table_widget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.test_table_widget)
        self.horizontal_layout_chose_test = QtWidgets.QHBoxLayout()
        self.horizontal_layout_chose_test.setObjectName("horizontal_layout_chose_test")
        self.clue_test3 = QtWidgets.QLabel(self.tab_tests)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clue_test3.setFont(font)
        self.clue_test3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clue_test3.setObjectName("clue_test3")
        self.horizontal_layout_chose_test.addWidget(self.clue_test3)
        self.chose_test = QtWidgets.QLabel(self.tab_tests)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chose_test.sizePolicy().hasHeightForWidth())
        self.chose_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chose_test.setFont(font)
        self.chose_test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chose_test.setText("")
        self.chose_test.setObjectName("chose_test")
        self.horizontal_layout_chose_test.addWidget(self.chose_test)
        self.verticalLayout_2.addLayout(self.horizontal_layout_chose_test)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.start_test_push_button = QtWidgets.QPushButton(self.tab_tests)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_test_push_button.setFont(font)
        self.start_test_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.start_test_push_button.setObjectName("start_test_push_button")
        self.horizontalLayout_4.addWidget(self.start_test_push_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tab_search1.addTab(self.tab_tests, "")
        self.tab_lessons = QtWidgets.QWidget()
        self.tab_lessons.setObjectName("tab_lessons")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_lessons)
        self.verticalLayout_4.setObjectName("work_vertical_layout")
        self.horizontal_layout_chenge_search_lesson = QtWidgets.QHBoxLayout()
        self.horizontal_layout_chenge_search_lesson.setObjectName("horizontal_layout_chenge_search_lesson")
        self.clue_lesson1 = QtWidgets.QLabel(self.tab_lessons)
        self.clue_lesson1.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clue_lesson1.setFont(font)
        self.clue_lesson1.setObjectName("clue_lesson1")
        self.horizontal_layout_chenge_search_lesson.addWidget(self.clue_lesson1)
        self.change_search_on_lesson_combo = QtWidgets.QComboBox(self.tab_lessons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_search_on_lesson_combo.sizePolicy().hasHeightForWidth())
        self.change_search_on_lesson_combo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.change_search_on_lesson_combo.setFont(font)
        self.change_search_on_lesson_combo.setObjectName("change_search_on_lesson_combo")
        self.change_search_on_lesson_combo.addItem("")
        self.change_search_on_lesson_combo.addItem("")
        self.horizontal_layout_chenge_search_lesson.addWidget(self.change_search_on_lesson_combo)
        spacerItem2 = QtWidgets.QSpacerItem(669, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_chenge_search_lesson.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontal_layout_chenge_search_lesson)
        self.horizontal_layout_edit_search_lesson = QtWidgets.QHBoxLayout()
        self.horizontal_layout_edit_search_lesson.setObjectName("horizontal_layout_edit_search_lesson")
        self.search_on_lessons_line_edit = QtWidgets.QLineEdit(self.tab_lessons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_on_lessons_line_edit.sizePolicy().hasHeightForWidth())
        self.search_on_lessons_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_on_lessons_line_edit.setFont(font)
        self.search_on_lessons_line_edit.setObjectName("search_on_lessons_line_edit")
        self.horizontal_layout_edit_search_lesson.addWidget(self.search_on_lessons_line_edit)
        self.find_lesson_button = QtWidgets.QPushButton(self.tab_lessons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.find_lesson_button.sizePolicy().hasHeightForWidth())
        self.find_lesson_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_lesson_button.setFont(font)
        self.find_lesson_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.find_lesson_button.setObjectName("find_lesson_button")
        self.horizontal_layout_edit_search_lesson.addWidget(self.find_lesson_button)
        self.refresh_lesson_button = QtWidgets.QPushButton(self.tab_lessons)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refresh_lesson_button.setFont(font)
        self.refresh_lesson_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.refresh_lesson_button.setObjectName("refresh_lesson_button")
        self.horizontal_layout_edit_search_lesson.addWidget(self.refresh_lesson_button)
        self.verticalLayout_4.addLayout(self.horizontal_layout_edit_search_lesson)
        self.clue_lesson2 = QtWidgets.QLabel(self.tab_lessons)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clue_lesson2.setFont(font)
        self.clue_lesson2.setObjectName("clue_lesson2")
        self.verticalLayout_4.addWidget(self.clue_lesson2)
        self.lessons_table_widget = QtWidgets.QTableWidget(self.tab_lessons)
        self.lessons_table_widget.setStyleSheet("color: rgb(0, 0, 0);\n"
                                                "background-color: rgb(255, 255, 255);")
        self.lessons_table_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.lessons_table_widget.setObjectName("lessons_table_widget")
        self.lessons_table_widget.setColumnCount(4)
        self.lessons_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lessons_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lessons_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lessons_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lessons_table_widget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.lessons_table_widget)
        self.horizontal_layout_chose_lesson = QtWidgets.QHBoxLayout()
        self.horizontal_layout_chose_lesson.setObjectName("horizontal_layout_chose_lesson")
        self.clue_lesson3 = QtWidgets.QLabel(self.tab_lessons)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clue_lesson3.setFont(font)
        self.clue_lesson3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clue_lesson3.setObjectName("clue_lesson3")
        self.horizontal_layout_chose_lesson.addWidget(self.clue_lesson3)
        self.chose_lesson = QtWidgets.QLabel(self.tab_lessons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chose_lesson.sizePolicy().hasHeightForWidth())
        self.chose_lesson.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chose_lesson.setFont(font)
        self.chose_lesson.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chose_lesson.setText("")
        self.chose_lesson.setObjectName("chose_lesson")
        self.horizontal_layout_chose_lesson.addWidget(self.chose_lesson)
        self.verticalLayout_4.addLayout(self.horizontal_layout_chose_lesson)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.start_lesson_push_button = QtWidgets.QPushButton(self.tab_lessons)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_lesson_push_button.setFont(font)
        self.start_lesson_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.start_lesson_push_button.setObjectName("start_lesson_push_button")
        self.horizontalLayout_2.addWidget(self.start_lesson_push_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tab_search1.addTab(self.tab_lessons, "")
        self.horizontalLayout.addWidget(self.tab_search1)
        self.main_tab_widget.addTab(self.tab_search, "")
        self.tab_appointment = QtWidgets.QWidget()
        self.tab_appointment.setObjectName("tab_appointment")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_appointment)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.appointment_test_list_widget = QtWidgets.QListWidget(self.tab_appointment)
        self.appointment_test_list_widget.setObjectName("appointment_test_list_widget")
        self.verticalLayout_5.addWidget(self.appointment_test_list_widget)
        self.horizontal_layout_chose_appointment_test = QtWidgets.QHBoxLayout()
        self.horizontal_layout_chose_appointment_test.setObjectName("horizontal_layout_chose_appointment_test")
        self.text_chose_appointment_test = QtWidgets.QLabel(self.tab_appointment)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_chose_appointment_test.setFont(font)
        self.text_chose_appointment_test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.text_chose_appointment_test.setObjectName("text_chose_appointment_test")
        self.horizontal_layout_chose_appointment_test.addWidget(self.text_chose_appointment_test)
        self.chose_appointment_test = QtWidgets.QLabel(self.tab_appointment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chose_appointment_test.sizePolicy().hasHeightForWidth())
        self.chose_appointment_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chose_appointment_test.setFont(font)
        self.chose_appointment_test.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chose_appointment_test.setText("")
        self.chose_appointment_test.setObjectName("chose_appointment_test")
        self.horizontal_layout_chose_appointment_test.addWidget(self.chose_appointment_test)
        self.verticalLayout_5.addLayout(self.horizontal_layout_chose_appointment_test)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.start_appointment_test_push_button = QtWidgets.QPushButton(self.tab_appointment)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.start_appointment_test_push_button.setFont(font)
        self.start_appointment_test_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.start_appointment_test_push_button.setObjectName("start_appointment_test_push_button")
        self.horizontalLayout_3.addWidget(self.start_appointment_test_push_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.main_tab_widget.addTab(self.tab_appointment, "")
        self.tab_result = QtWidgets.QWidget()
        self.tab_result.setObjectName("tab_result")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_result)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontal_layout_2 = QtWidgets.QHBoxLayout()
        self.horizontal_layout_2.setObjectName("horizontal_layout_2")
        self.updata_push_button = QtWidgets.QPushButton(self.tab_result)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updata_push_button.setFont(font)
        self.updata_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.updata_push_button.setObjectName("updata_push_button")
        self.horizontal_layout_2.addWidget(self.updata_push_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_2.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontal_layout_2)
        self.result_grid = QtWidgets.QGridLayout()
        self.result_grid.setContentsMargins(3, 3, 3, 3)
        self.result_grid.setSpacing(5)
        self.result_grid.setObjectName("result_grid")
        self.verticalLayout_3.addLayout(self.result_grid)
        spacerItem6 = QtWidgets.QSpacerItem(20, 383, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.main_tab_widget.addTab(self.tab_result, "")
        self.verticalLayout.addWidget(self.main_tab_widget)

        self.retranslateUi(ListSearch)
        self.main_tab_widget.setCurrentIndex(0)
        self.tab_search1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ListSearch)

    def retranslateUi(self, ListSearch):
        _translate = QtCore.QCoreApplication.translate
        ListSearch.setWindowTitle(_translate("ListSearch", "Form"))
        self.clue_test1.setText(_translate("ListSearch", "Искать через:"))
        self.change_search_on_test_combo_box.setItemText(0, _translate("ListSearch", "Имя"))
        self.change_search_on_test_combo_box.setItemText(1, _translate("ListSearch", "Тег"))
        self.search_on_tests_line_edit.setPlaceholderText(_translate("ListSearch", "Введите название..."))
        self.find_test_button.setText(_translate("ListSearch", "Поиск"))
        self.refresh_test_button.setText(_translate("ListSearch", "Очистить"))
        self.clue_test2.setText(_translate("ListSearch", "Чтобы выбрать нажми два раза"))
        item = self.test_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("ListSearch", "Название"))
        item = self.test_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("ListSearch", "Тип"))
        item = self.test_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("ListSearch", "Вопросов"))
        item = self.test_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("ListSearch", "Время"))
        self.clue_test3.setText(_translate("ListSearch", "Выбранный тест:"))
        self.start_test_push_button.setText(_translate("ListSearch", "Начать"))
        self.tab_search1.setTabText(self.tab_search1.indexOf(self.tab_tests), _translate("ListSearch", "Тесты"))
        self.clue_lesson1.setText(_translate("ListSearch", "Искать через:"))
        self.change_search_on_lesson_combo.setItemText(0, _translate("ListSearch", "Имя"))
        self.change_search_on_lesson_combo.setItemText(1, _translate("ListSearch", "Тег"))
        self.search_on_lessons_line_edit.setPlaceholderText(_translate("ListSearch", "Введите название..."))
        self.find_lesson_button.setText(_translate("ListSearch", "Поиск"))
        self.refresh_lesson_button.setText(_translate("ListSearch", "Очистить"))
        self.clue_lesson2.setText(_translate("ListSearch", "Чтобы выбрать нажми два раза"))
        item = self.lessons_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("ListSearch", "Название"))
        item = self.lessons_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("ListSearch", "Тип"))
        item = self.lessons_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("ListSearch", "Вопросов"))
        item = self.lessons_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("ListSearch", "Время"))
        self.clue_lesson3.setText(_translate("ListSearch", "Выбранный материал:"))
        self.start_lesson_push_button.setText(_translate("ListSearch", "Начать"))
        self.tab_search1.setTabText(self.tab_search1.indexOf(self.tab_lessons),
                                    _translate("ListSearch", "Учебные материалы"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_search),
                                        _translate("ListSearch", "Поиск"))
        self.text_chose_appointment_test.setText(_translate("ListSearch", "Выбранный тест:"))
        self.start_appointment_test_push_button.setText(_translate("ListSearch", "Начать"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_appointment),
                                        _translate("ListSearch", "Назначенные тесты"))
        self.updata_push_button.setText(_translate("ListSearch", "Обновить"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_result),
                                        _translate("ListSearch", "Результат"))
