from PyQt5 import QtCore, QtGui, QtWidgets
from image import resourse


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(900, 600)
        MainWindow.setStyleSheet("background-color: rgb(203, 122, 9); color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_main_window = QtWidgets.QVBoxLayout()
        self.widget_main_window.setSpacing(0)
        self.widget_main_window.setObjectName("widget_main_window")
        self.top_widget_main_window = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_widget_main_window.sizePolicy().hasHeightForWidth())
        self.top_widget_main_window.setSizePolicy(sizePolicy)
        self.top_widget_main_window.setMinimumSize(QtCore.QSize(0, 30))
        self.top_widget_main_window.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top_widget_main_window.setStyleSheet("background-color: rgb(203, 122, 9);")
        self.top_widget_main_window.setObjectName("top_widget_main_window")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_widget_main_window)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_main_push_button = QtWidgets.QPushButton(self.top_widget_main_window)
        self.to_main_push_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_main_push_button.setFont(font)
        self.to_main_push_button.setStyleSheet("QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                               "QPushButton:disabled{ background:#a2979c; }")
        self.to_main_push_button.setObjectName("to_main_push_button")
        self.horizontalLayout.addWidget(self.to_main_push_button)
        self.refresh_push_button = QtWidgets.QPushButton(self.top_widget_main_window)
        self.refresh_push_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.refresh_push_button.setFont(font)
        self.refresh_push_button.setStyleSheet("QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                               "QPushButton:disabled{ background:#a2979c; }")
        self.refresh_push_button.setObjectName("refresh_push_button")
        self.horizontalLayout.addWidget(self.refresh_push_button)
        spacerItem = QtWidgets.QSpacerItem(769, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exit_push_button = QtWidgets.QPushButton(self.top_widget_main_window)
        self.exit_push_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exit_push_button.setFont(font)
        self.exit_push_button.setStyleSheet("QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                            "QPushButton:disabled{ background:#a2979c; }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main_window_prefix/profile_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_push_button.setIcon(icon)
        self.exit_push_button.setIconSize(QtCore.QSize(25, 25))
        self.exit_push_button.setObjectName("exit_push_button")
        self.horizontalLayout.addWidget(self.exit_push_button)
        self.widget_main_window.addWidget(self.top_widget_main_window)
        self.work_widget = QtWidgets.QWidget(self.centralwidget)
        self.work_widget.setStyleSheet("background-color: rgb(13, 130, 149);")
        self.work_widget.setObjectName("work_widget")
        self.work_vertical_layout = QtWidgets.QVBoxLayout(self.work_widget)
        self.work_vertical_layout.setContentsMargins(6, 6, 6, 6)
        self.work_vertical_layout.setSpacing(6)
        self.work_vertical_layout.setObjectName("work_vertical_layout")
        self.widget_main_window.addWidget(self.work_widget)
        self.verticalLayout_2.addLayout(self.widget_main_window)
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        # self.menubar.setObjectName("menubar")
        # self.menu = QtWidgets.QMenu(self.menubar)
        # self.menu.setObjectName("menu")
        # MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondsaf_sdfga = QtWidgets.QAction(MainWindow)
        self.actiondsaf_sdfga.setObjectName("actiondsaf_sdfga")
        self.actionasdfasd = QtWidgets.QAction(MainWindow)
        self.actionasdfasd.setObjectName("actionasdfasd")
        # self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.to_main_push_button.setText(_translate("MainWindow", "На главную"))
        self.refresh_push_button.setText(_translate("MainWindow", "Обновить все данные"))
        self.exit_push_button.setText(_translate("MainWindow", "Выход"))
        # self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.actiondsaf_sdfga.setText(_translate("MainWindow", "dsaf sdfga"))
        self.actionasdfasd.setText(_translate("MainWindow", "asdfasd"))
