# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultUser(object):
    def setupUi(self, ResultUser):
        ResultUser.setObjectName("ResultUser")
        ResultUser.resize(744, 496)
        ResultUser.setStyleSheet("background: rgb(13, 120, 149);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ResultUser)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.vertical_layout_2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        self.result_list_widget = QtWidgets.QListWidget(ResultUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_list_widget.sizePolicy().hasHeightForWidth())
        self.result_list_widget.setSizePolicy(sizePolicy)
        self.result_list_widget.setMinimumSize(QtCore.QSize(290, 300))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.result_list_widget.setFont(font)
        self.result_list_widget.setObjectName("result_list_widget")
        self.vertical_layout_2.addWidget(self.result_list_widget)
        self.show_result_push_button = QtWidgets.QPushButton(ResultUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_result_push_button.sizePolicy().hasHeightForWidth())
        self.show_result_push_button.setSizePolicy(sizePolicy)
        self.show_result_push_button.setMinimumSize(QtCore.QSize(290, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_result_push_button.setFont(font)
        self.show_result_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.show_result_push_button.setObjectName("show_result_push_button")
        self.vertical_layout_2.addWidget(self.show_result_push_button)
        self.horizontal_layout.addLayout(self.vertical_layout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout.addItem(spacerItem)
        self.result_vertical_layout = QtWidgets.QVBoxLayout()
        self.result_vertical_layout.setContentsMargins(3, 3, 3, 3)
        self.result_vertical_layout.setObjectName("result_vertical_layout")
        self.horizontal_layout.addLayout(self.result_vertical_layout)
        self.verticalLayout_3.addLayout(self.horizontal_layout)

        self.retranslateUi(ResultUser)
        QtCore.QMetaObject.connectSlotsByName(ResultUser)

    def retranslateUi(self, ResultUser):
        _translate = QtCore.QCoreApplication.translate
        ResultUser.setWindowTitle(_translate("ResultUser", "Form"))
        self.show_result_push_button.setText(_translate("ResultUser", "Посмотреть"))
