# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(880, 550)
        Settings.setMinimumSize(QtCore.QSize(880, 550))
        Settings.setMaximumSize(QtCore.QSize(880, 550))
        Settings.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Settings)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hint_conniction_label = QtWidgets.QLabel(self.frame)
        self.hint_conniction_label.setObjectName("hint_conniction_label")
        self.horizontalLayout_2.addWidget(self.hint_conniction_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.connection_field_grid_layout = QtWidgets.QGridLayout()
        self.connection_field_grid_layout.setObjectName("connection_field_grid_layout")
        self.hint_host_label = QtWidgets.QLabel(self.frame)
        self.hint_host_label.setObjectName("hint_host_label")
        self.connection_field_grid_layout.addWidget(self.hint_host_label, 0, 0, 1, 1)
        self.host_line_edit = QtWidgets.QLineEdit(self.frame)
        self.host_line_edit.setMaximumSize(QtCore.QSize(390, 16777215))
        self.host_line_edit.setObjectName("host_line_edit")
        self.connection_field_grid_layout.addWidget(self.host_line_edit, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_field_grid_layout.addItem(spacerItem1, 0, 2, 1, 1)
        self.hint_port_label = QtWidgets.QLabel(self.frame)
        self.hint_port_label.setObjectName("hint_port_label")
        self.connection_field_grid_layout.addWidget(self.hint_port_label, 1, 0, 1, 1)
        self.port_line_edit = QtWidgets.QLineEdit(self.frame)
        self.port_line_edit.setMaximumSize(QtCore.QSize(390, 16777215))
        self.port_line_edit.setObjectName("port_line_edit")
        self.connection_field_grid_layout.addWidget(self.port_line_edit, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_field_grid_layout.addItem(spacerItem2, 1, 2, 1, 1)
        self.hint_password_label = QtWidgets.QLabel(self.frame)
        self.hint_password_label.setObjectName("hint_password_label")
        self.connection_field_grid_layout.addWidget(self.hint_password_label, 2, 0, 1, 1)
        self.password_line_edit = QtWidgets.QLineEdit(self.frame)
        self.password_line_edit.setMaximumSize(QtCore.QSize(390, 16777215))
        self.password_line_edit.setObjectName("password_line_edit")
        self.connection_field_grid_layout.addWidget(self.password_line_edit, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connection_field_grid_layout.addItem(spacerItem3, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.connection_field_grid_layout)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem4 = QtWidgets.QSpacerItem(20, 376, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.ok_push_button = QtWidgets.QPushButton(Settings)
        self.ok_push_button.setObjectName("ok_push_button")
        self.horizontalLayout.addWidget(self.ok_push_button)
        self.cancel_push_button = QtWidgets.QPushButton(Settings)
        self.cancel_push_button.setObjectName("cancel_push_button")
        self.horizontalLayout.addWidget(self.cancel_push_button)
        self.apply_push_button = QtWidgets.QPushButton(Settings)
        self.apply_push_button.setObjectName("apply_push_button")
        self.horizontalLayout.addWidget(self.apply_push_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.hint_conniction_label.setText(_translate("Settings", "Database connection"))
        self.hint_host_label.setText(_translate("Settings", "Host:"))
        self.hint_port_label.setText(_translate("Settings", "Port:"))
        self.hint_password_label.setText(_translate("Settings", "Password:"))
        self.ok_push_button.setText(_translate("Settings", "OK"))
        self.cancel_push_button.setText(_translate("Settings", "Cancel"))
        self.apply_push_button.setText(_translate("Settings", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
