# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(833, 435)
        Analysis.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(13, 120, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Analysis)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Analysis)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane\n"
"{\n"
"    border:1px;\n"
"    background: rgb(203, 122, 9);\n"
"}\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    color: white;\n"
"    background: rgb(13, 120, 149);\n"
"    min-width: 25ex;\n"
"    min-height: 8ex;\n"
"}\n"
"\n"
"QTabBar::tab::selected\n"
"{\n"
"    background: rgb(213, 122, 9);\n"
"}\n"
"\n"
"QTabBar::tab::hover\n"
"{\n"
"    background: rgb(203, 112, 9);\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.result_user = QtWidgets.QWidget()
        self.result_user.setObjectName("result_user")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.result_user)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vertical_layout_list = QtWidgets.QVBoxLayout()
        self.vertical_layout_list.setObjectName("vertical_layout_list")
        self.result_user_list_widget = QtWidgets.QListWidget(self.result_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_user_list_widget.sizePolicy().hasHeightForWidth())
        self.result_user_list_widget.setSizePolicy(sizePolicy)
        self.result_user_list_widget.setMinimumSize(QtCore.QSize(450, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_user_list_widget.setFont(font)
        self.result_user_list_widget.setObjectName("result_user_list_widget")
        self.vertical_layout_list.addWidget(self.result_user_list_widget)
        self.show_result_user_button = QtWidgets.QPushButton(self.result_user)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_result_user_button.sizePolicy().hasHeightForWidth())
        self.show_result_user_button.setSizePolicy(sizePolicy)
        self.show_result_user_button.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_result_user_button.setFont(font)
        self.show_result_user_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.show_result_user_button.setObjectName("show_result_user_button")
        self.vertical_layout_list.addWidget(self.show_result_user_button)
        self.horizontalLayout_2.addLayout(self.vertical_layout_list)
        spacerItem = QtWidgets.QSpacerItem(458, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.vertical_layout_graph_result_user = QtWidgets.QVBoxLayout()
        self.vertical_layout_graph_result_user.setContentsMargins(3, 3, 3, 3)
        self.vertical_layout_graph_result_user.setSpacing(6)
        self.vertical_layout_graph_result_user.setObjectName("vertical_layout_graph_result_user")
        self.horizontalLayout_2.addLayout(self.vertical_layout_graph_result_user)
        self.tabWidget.addTab(self.result_user, "")
        self.statistic_of_test = QtWidgets.QWidget()
        self.statistic_of_test.setObjectName("statistic_of_test")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.statistic_of_test)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vertical_layout_list2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_list2.setObjectName("vertical_layout_list2")
        self.result_test_list_widget = QtWidgets.QListWidget(self.statistic_of_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_test_list_widget.sizePolicy().hasHeightForWidth())
        self.result_test_list_widget.setSizePolicy(sizePolicy)
        self.result_test_list_widget.setMinimumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_test_list_widget.setFont(font)
        self.result_test_list_widget.setObjectName("result_test_list_widget")
        self.vertical_layout_list2.addWidget(self.result_test_list_widget)
        self.show_result_test_button = QtWidgets.QPushButton(self.statistic_of_test)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_result_test_button.sizePolicy().hasHeightForWidth())
        self.show_result_test_button.setSizePolicy(sizePolicy)
        self.show_result_test_button.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.show_result_test_button.setFont(font)
        self.show_result_test_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.show_result_test_button.setObjectName("show_result_test_button")
        self.vertical_layout_list2.addWidget(self.show_result_test_button)
        self.horizontalLayout_3.addLayout(self.vertical_layout_list2)
        spacerItem1 = QtWidgets.QSpacerItem(458, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.vertical_layout_graph_result_test = QtWidgets.QVBoxLayout()
        self.vertical_layout_graph_result_test.setContentsMargins(3, 3, 3, 3)
        self.vertical_layout_graph_result_test.setObjectName("vertical_layout_graph_result_test")
        self.horizontalLayout_3.addLayout(self.vertical_layout_graph_result_test)
        self.tabWidget.addTab(self.statistic_of_test, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Analysis)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        _translate = QtCore.QCoreApplication.translate
        Analysis.setWindowTitle(_translate("Analysis", "Form"))
        self.show_result_user_button.setText(_translate("Analysis", "Посмотреть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result_user), _translate("Analysis", "Результаты пользователей"))
        self.show_result_test_button.setText(_translate("Analysis", "Посмотреть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistic_of_test), _translate("Analysis", "Статистика тестов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Analysis = QtWidgets.QWidget()
    ui = Ui_Analysis()
    ui.setupUi(Analysis)
    Analysis.show()
    sys.exit(app.exec_())
