# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateLesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateLesson(object):
    def setupUi(self, CreateLesson):
        CreateLesson.setObjectName("CreateLesson")
        CreateLesson.resize(916, 632)
        CreateLesson.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(13, 130, 149);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CreateLesson)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hint_label = QtWidgets.QLabel(CreateLesson)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hint_label.setFont(font)
        self.hint_label.setObjectName("hint_label")
        self.horizontalLayout_2.addWidget(self.hint_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.text_edit = QtWidgets.QTextEdit(CreateLesson)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.text_edit.setFont(font)
        self.text_edit.setObjectName("text_edit")
        self.verticalLayout.addWidget(self.text_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.create_push_button = QtWidgets.QPushButton(CreateLesson)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.create_push_button.setFont(font)
        self.create_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.create_push_button.setObjectName("create_push_button")
        self.horizontalLayout.addWidget(self.create_push_button)
        self.close_push_button = QtWidgets.QPushButton(CreateLesson)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.close_push_button.setFont(font)
        self.close_push_button.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.close_push_button.setObjectName("close_push_button")
        self.horizontalLayout.addWidget(self.close_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CreateLesson)
        QtCore.QMetaObject.connectSlotsByName(CreateLesson)

    def retranslateUi(self, CreateLesson):
        _translate = QtCore.QCoreApplication.translate
        CreateLesson.setWindowTitle(_translate("CreateLesson", "Form"))
        self.hint_label.setText(_translate("CreateLesson", "Текст учебного материала"))
        self.text_edit.setPlaceholderText(_translate("CreateLesson", "Введите текст учебного материала..."))
        self.create_push_button.setText(_translate("CreateLesson", "Создать"))
        self.close_push_button.setText(_translate("CreateLesson", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateLesson = QtWidgets.QWidget()
    ui = Ui_CreateLesson()
    ui.setupUi(CreateLesson)
    CreateLesson.show()
    sys.exit(app.exec_())
