# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateTestingTypeQuest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateTestingTypeQuest(object):
    def setupUi(self, CreateTestingTypeQuest):
        CreateTestingTypeQuest.setObjectName("CreateTestingTypeQuest")
        CreateTestingTypeQuest.resize(765, 236)
        CreateTestingTypeQuest.setMinimumSize(QtCore.QSize(0, 0))
        CreateTestingTypeQuest.setMaximumSize(QtCore.QSize(16777215, 16777215))
        CreateTestingTypeQuest.setStyleSheet("color: rgb(255, 255, 255);\n"
                                             "background-color: rgb(13, 130, 149);\n"
                                             "")
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateTestingTypeQuest)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clue_label_type = QtWidgets.QLabel(CreateTestingTypeQuest)
        self.clue_label_type.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.clue_label_type.setFont(font)
        self.clue_label_type.setObjectName("clue_label_type")
        self.horizontalLayout.addWidget(self.clue_label_type)
        self.type_testing_combo_box = QtWidgets.QComboBox(CreateTestingTypeQuest)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.type_testing_combo_box.setFont(font)
        self.type_testing_combo_box.setObjectName("type_testing_combo_box")
        self.horizontalLayout.addWidget(self.type_testing_combo_box)
        self.check_properties = QtWidgets.QPushButton(CreateTestingTypeQuest)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.check_properties.setFont(font)
        self.check_properties.setStyleSheet("background-color: rgb(213, 122, 9);")
        self.check_properties.setObjectName("check_properties")
        self.horizontalLayout.addWidget(self.check_properties)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.worl_vertical_layout = QtWidgets.QVBoxLayout()
        self.worl_vertical_layout.setObjectName("worl_vertical_layout")
        self.verticalLayout.addLayout(self.worl_vertical_layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 176, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(CreateTestingTypeQuest)
        QtCore.QMetaObject.connectSlotsByName(CreateTestingTypeQuest)

    def retranslateUi(self, CreateTestingTypeQuest):
        _translate = QtCore.QCoreApplication.translate
        CreateTestingTypeQuest.setWindowTitle(_translate("CreateTestingTypeQuest", "Form"))
        self.clue_label_type.setText(_translate("CreateTestingTypeQuest", "Тип задания:"))
        self.check_properties.setText(_translate("CreateTestingTypeQuest", "Принять"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    CreateTestingTypeQuest = QtWidgets.QWidget()
    ui = Ui_CreateTestingTypeQuest()
    ui.setupUi(CreateTestingTypeQuest)
    CreateTestingTypeQuest.show()
    sys.exit(app.exec_())
