# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckResultTesting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckResultTesting(object):
    def setupUi(self, CheckResultTesting):
        CheckResultTesting.setObjectName("CheckResultTesting")
        CheckResultTesting.resize(940, 527)
        CheckResultTesting.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(13, 130, 149);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CheckResultTesting)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontal_layout_top = QtWidgets.QHBoxLayout()
        self.horizontal_layout_top.setObjectName("horizontal_layout_top")
        self.clue = QtWidgets.QLabel(CheckResultTesting)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clue.setFont(font)
        self.clue.setObjectName("clue")
        self.horizontal_layout_top.addWidget(self.clue)
        self.name_user_label = QtWidgets.QLabel(CheckResultTesting)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_user_label.setFont(font)
        self.name_user_label.setText("")
        self.name_user_label.setObjectName("name_user_label")
        self.horizontal_layout_top.addWidget(self.name_user_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout_top.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontal_layout_top)
        self.quests_tab_widget = QtWidgets.QTabWidget(CheckResultTesting)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.quests_tab_widget.setFont(font)
        self.quests_tab_widget.setStyleSheet("QTabWidget::pane\n"
                                             "{\n"
                                             "    border:1px;\n"
                                             "    background: rgb(203, 122, 9);\n"
                                             "}\n"
                                             "\n"
                                             "QTabBar::tab\n"
                                             "{\n"
                                             "    color: white;\n"
                                             "    background: rgb(13, 120, 149);\n"
                                             "    min-width: 25ex;\n"
                                             "    min-height: 8ex;\n"
                                             "}\n"
                                             "\n"
                                             "QTabBar::tab::selected\n"
                                             "{\n"
                                             "    background: rgb(213, 122, 9);\n"
                                             "}\n"
                                             "\n"
                                             "QTabBar::tab::hover\n"
                                             "{\n"
                                             "    background: rgb(203, 112, 9);\n"
                                             "}\n"
                                             "")
        self.quests_tab_widget.setObjectName("quests_tab_widget")
        self.verticalLayout.addWidget(self.quests_tab_widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 226, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.complete_button = QtWidgets.QPushButton(CheckResultTesting)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.complete_button.setFont(font)
        self.complete_button.setStyleSheet("QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                           "QPushButton:disabled{ background:#a2979c; }")
        self.complete_button.setObjectName("complete_button")
        self.gridLayout.addWidget(self.complete_button, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.stop_button = QtWidgets.QPushButton(CheckResultTesting)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("QPushButton:enabled{ color: rgb(255, 255, 255); }\n"
                                       "QPushButton:disabled{ background:#a2979c; }")
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(CheckResultTesting)
        QtCore.QMetaObject.connectSlotsByName(CheckResultTesting)

    def retranslateUi(self, CheckResultTesting):
        _translate = QtCore.QCoreApplication.translate
        CheckResultTesting.setWindowTitle(_translate("CheckResultTesting", "Form"))
        self.clue.setText(_translate("CheckResultTesting", "Тестируемый:"))
        self.complete_button.setText(_translate("CheckResultTesting", "Завершить проверку"))
        self.stop_button.setText(_translate("CheckResultTesting", "Отложить проверку"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    CheckResultTesting = QtWidgets.QWidget()
    ui = Ui_CheckResultTesting()
    ui.setupUi(CheckResultTesting)
    CheckResultTesting.show()
    sys.exit(app.exec_())
